# Generated by Django 4.1.6 on 2023-02-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('N', 'Not Started'), ('S', 'Started'), ('C', 'Completed'), ('A', 'Abandoned')], default='N', max_length=1)),
                ('notes', models.TextField(max_length=1000)),
                ('author', models.ManyToManyField(to='main_app.author')),
            ],
        ),
    ]
