# Generated by Django 4.1.6 on 2023-02-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_media_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='score',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('B', 'Book'), ('P', 'Podcast'), ('M', 'Movie'), ('A', 'Article'), ('V', 'Video'), ('P', 'Paper')], default='B', max_length=100),
        ),
    ]
